[build]
  base = "client"
  publish = "client/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-railway-app.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-railway-app.railway.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-railway-app.railway.app"

[context.branch-deploy.environment]
  VITE_API_URL = "https://your-railway-app.railway.app"
