[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'rm -rf node_modules package-lock.json',
  'npm install --no-optional',
  'npm install @rollup/rollup-linux-x64-gnu --save-optional'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
MAX_FILE_SIZE = '50mb'
BODY_LIMIT = '50mb'
