[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodeVersion = "20.18.0"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Mount persistent volume for database storage
[[deploy.volumes]]
mountPath = "/app/data"
name = "database-storage"
